version: "3.9"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   # ホストとコンテナのポートをマッピング
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host   # ← ここを追加
